# -*- coding: utf-8 -*-
"""Лаб№3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QV0-Qu5NEUZPN1McyFDSfu-1g5IbBQqO

Условные конструкции
"""

language = "english"
if language == "english":
  print("Hello")
print("End")

language = "russian"
if language == "english":
  print("Hello")
else:
  print("Привет")
  print("Спишь?")
print("End")

language = "japanese"
if language == "english":
  print("Hello")
  print("World")
elif language == "german":
  print("Hallo")
  print("Welt")
elif language == "japanese":
  print("konichiwa")
  print("nya^^") 
else:
  print("Привет")
  print("мир")

language = "italian"
if language == "english":
  print("Hello")
  print("World")
elif language == "german":
  print("Hallo")
  print("Welt")
elif language == "japanese":
  print("konichiwa")
  print("nya^^") 
else:
  print("Привет")
  print("мир")

language = "english"
daytime = "morning"
if language == "english":
  print("Hello")
  if daytime == "morning":
   print("good morning")
  else:
   print("good evening")

"""Задания для самостоятельного выполнения

№1
"""

month=["январь", "февраль", "март", "апрель", "май", "июнь", "июль", "август", "сентябрь", "октябрь", "ноябрь", "декабрь"]
n=int(input())
print(month[n-1])

"""№2"""

x=int(input())
if x%2==0:
  print("чётное")
else:
  print("нечётное")

"""№3"""

N=int(input())
if N>40:
  print("STONKS")
else:
  print("not stonks(")

"""№4"""

def is_year_leap():
  year=int(input("Год "))
  if year%4==0 or (year%100!=0 and year%400==0):
    return True
  else:
    return False
is_year_leap()

"""№5"""

def is_prime():
  n=int(input())
  d=2
  while n%d!=0:
    d+=1
  if d==n:
    return True
  else:
    return False
is_prime()

"""№6"""

a=float(input("a = "))
b=float(input("b = "))
if (a/b>=3.6) or (b==[(-138/2)**1.3, abs(((-69/28)**5.1)*4)]):
  print(b,a)
else:
  print(a,b)

"""№7"""

n1=int(input())
n2=int(input()) 
n3=int(input())
n4=int(input())
n5=int(input())
summa1=0
summa2=0
summa3=0
if n1!=n2!=n3!=n4!=n5:
  print("Числа уникальные")
else:
  print("Числа НЕУНИКАЛЬНЫЕ")
if n1%2==0:
  summa1+=1
if n2%2==0:
  summa1+=1
if n3%2==0:
  summa1+=1
if n4%2==0:
  summa1+=1
if n5%2==0:
  summa1+=1
print("Чётных чисел ",summa1)

if n1<0:
  summa2+=1
if n2<0:
  summa2+=1
if n3<0:
  summa2+=1
if n4<0:
  summa2+=1
if n5<0:
  summa2+=1
print("Отрицательных чисел ", summa2)

if  -256<=n1<=1024:
  summa3+=1
if -256<=n2<=1024:
   summa3+=1
if -256<=n3<=1024:
   summa3+=1
if  -256<=n4<=1024:
  summa3+=1
if -256<=n5<=1924:
  summa3+=1
print("Чисел в промежутке ", summa3)